# Staging build command
[context.staging]
  command = "npm run staging"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://energybubble.netlify.com/*"
  to = "https://energybubble.net/:splat"
  status = 301
  force = true
